CREATE TABLE IF NOT EXISTS `oraculo`.`news` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `link` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `labels` TEXT NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `cdate` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `oraculo`.`user_parameter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` TEXT NOT NULL,
  `key` VARCHAR(20) NOT NULL,
  `value` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
